"""initial_schema

Revision ID: f7aa706477a3
Revises: 
Create Date: 2026-09-08 15:58:15.745641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f7aa706477a3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.create_table('editions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('introduction', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('low_signal_notice', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_editions_date'), 'editions', ['date'], unique=True)
    op.create_index(op.f('ix_editions_status'), 'editions', ['status'], unique=False)
    op.create_table('editorial_configurations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_editorial_configurations_key'), 'editorial_configurations', ['key'], unique=True)
    op.create_table('editorial_memories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('memory_type', sa.String(length=50), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_editorial_memories_key'), 'editorial_memories', ['key'], unique=False)
    op.create_index(op.f('ix_editorial_memories_memory_type'), 'editorial_memories', ['memory_type'], unique=False)
    op.create_index('ix_memory_type_key', 'editorial_memories', ['memory_type', 'key'], unique=True)
    op.create_table('pipeline_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.String(length=100), nullable=False),
    sa.Column('edition_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('logs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_runs_edition_date'), 'pipeline_runs', ['edition_date'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_run_id'), 'pipeline_runs', ['run_id'], unique=True)
    op.create_index(op.f('ix_pipeline_runs_status'), 'pipeline_runs', ['status'], unique=False)
    op.create_table('stories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('edition_id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('why_it_matters', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_lead', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['edition_id'], ['editions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stories_edition_id'), 'stories', ['edition_id'], unique=False)
    op.create_index('ix_stories_edition_slug', 'stories', ['edition_id', 'slug'], unique=True)
    op.create_index(op.f('ix_stories_slug'), 'stories', ['slug'], unique=False)
    op.create_index(op.f('ix_stories_status'), 'stories', ['status'], unique=False)
    op.create_table('story_candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('edition_id', sa.UUID(), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('normalized_text', sa.Text(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('significance_score', sa.Float(), nullable=False),
    sa.Column('novelty_score', sa.Float(), nullable=False),
    sa.Column('evidence_score', sa.Float(), nullable=False),
    sa.Column('saturation_score', sa.Float(), nullable=False),
    sa.Column('feedback_bias', sa.Float(), nullable=False),
    sa.Column('composite_score', sa.Float(), nullable=False),
    sa.Column('selected', sa.Boolean(), nullable=False),
    sa.Column('rejected_reason', sa.Text(), nullable=True),
    sa.Column('cluster_id', sa.String(length=100), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['edition_id'], ['editions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_candidates_cluster_id'), 'story_candidates', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_story_candidates_composite_score'), 'story_candidates', ['composite_score'], unique=False)
    op.create_index(op.f('ix_story_candidates_discovered_at'), 'story_candidates', ['discovered_at'], unique=False)
    op.create_index(op.f('ix_story_candidates_edition_id'), 'story_candidates', ['edition_id'], unique=False)
    op.create_index(op.f('ix_story_candidates_selected'), 'story_candidates', ['selected'], unique=False)
    op.create_index(op.f('ix_story_candidates_url'), 'story_candidates', ['url'], unique=False)
    op.create_table('feedbacks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('story_id', sa.UUID(), nullable=False),
    sa.Column('vote', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_feedback_story_session', 'feedbacks', ['story_id', 'session_id'], unique=True)
    op.create_index(op.f('ix_feedbacks_created_at'), 'feedbacks', ['created_at'], unique=False)
    op.create_index(op.f('ix_feedbacks_session_id'), 'feedbacks', ['session_id'], unique=False)
    op.create_index(op.f('ix_feedbacks_story_id'), 'feedbacks', ['story_id'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('story_id', sa.UUID(), nullable=True),
    sa.Column('candidate_id', sa.UUID(), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('publisher', sa.String(length=255), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['story_candidates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_candidate_id'), 'sources', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_sources_story_id'), 'sources', ['story_id'], unique=False)
    op.create_index(op.f('ix_sources_url'), 'sources', ['url'], unique=False)
    op.create_table('story_categories',
    sa.Column('story_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('story_id', 'category_id')
    )
    op.execute("""
        CREATE INDEX ix_stories_fts ON stories 
        USING gin(to_tsvector('english', title || ' ' || summary || ' ' || why_it_matters))
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS ix_stories_fts")
    op.drop_table('story_categories')
    op.drop_index(op.f('ix_sources_url'), table_name='sources')
    op.drop_index(op.f('ix_sources_story_id'), table_name='sources')
    op.drop_index(op.f('ix_sources_candidate_id'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_feedbacks_story_id'), table_name='feedbacks')
    op.drop_index(op.f('ix_feedbacks_session_id'), table_name='feedbacks')
    op.drop_index(op.f('ix_feedbacks_created_at'), table_name='feedbacks')
    op.drop_index('ix_feedback_story_session', table_name='feedbacks')
    op.drop_table('feedbacks')
    op.drop_index(op.f('ix_story_candidates_url'), table_name='story_candidates')
    op.drop_index(op.f('ix_story_candidates_selected'), table_name='story_candidates')
    op.drop_index(op.f('ix_story_candidates_edition_id'), table_name='story_candidates')
    op.drop_index(op.f('ix_story_candidates_discovered_at'), table_name='story_candidates')
    op.drop_index(op.f('ix_story_candidates_composite_score'), table_name='story_candidates')
    op.drop_index(op.f('ix_story_candidates_cluster_id'), table_name='story_candidates')
    op.drop_table('story_candidates')
    op.drop_index(op.f('ix_stories_status'), table_name='stories')
    op.drop_index(op.f('ix_stories_slug'), table_name='stories')
    op.drop_index('ix_stories_edition_slug', table_name='stories')
    op.drop_index(op.f('ix_stories_edition_id'), table_name='stories')
    op.drop_table('stories')
    op.drop_index(op.f('ix_pipeline_runs_status'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_run_id'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_edition_date'), table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    op.drop_index('ix_memory_type_key', table_name='editorial_memories')
    op.drop_index(op.f('ix_editorial_memories_memory_type'), table_name='editorial_memories')
    op.drop_index(op.f('ix_editorial_memories_key'), table_name='editorial_memories')
    op.drop_table('editorial_memories')
    op.drop_index(op.f('ix_editorial_configurations_key'), table_name='editorial_configurations')
    op.drop_table('editorial_configurations')
    op.drop_index(op.f('ix_editions_status'), table_name='editions')
    op.drop_index(op.f('ix_editions_date'), table_name='editions')
    op.drop_table('editions')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
